repos:
  - repo: local
    hooks:
      - id: biome
        name: biome
        entry: npm run lint
        language: system
        pass_filenames: false
      - id: typecheck
        name: typecheck
        entry: npm run typecheck
        language: system
        pass_filenames: false
